### ISSUE TITLE
关于页脚的版权声明

### ISSUE THREAD

**Issue by THU-Pieris** [izuolan/next-craft#1]
首先非常感谢您的这个项目！一直嘴馋隔壁notion的博客，没想到craft也已经有了！

页脚的版权声明处，显示的是BY-SA，但是链接却指向的BY，截图如下：
<img width="574" alt="Snipaste_2022-05-31_14-07-09" src="https://user-images.githubusercontent.com/49369792/171104254-0dad96ae-1b05-42ac-a56f-145ae68aaf14.png">

测试页面为 https://next-craft.vercel.app 。

**Comment by izuolan** [comment]
谢谢, 我现在才看到哈哈哈. 改过来了~
